In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
## Introduction to Tensors
#Pytorch tensors are created using torch.Tensor ()

# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python Integer
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
vector.shape

tensor([7, 7])
1


torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# TENSPR
TENSOR = torch.tensor([[[1, 2, 4, 7, 8],
                        [6, 8, 2, 9, 15],
                        [8, 87, 6, 5, 5],
                        [76, 5, 2, 1, 3]]])
TENSOR

tensor([[[ 1,  2,  4,  7,  8],
         [ 6,  8,  2,  9, 15],
         [ 8, 87,  6,  5,  5],
         [76,  5,  2,  1,  3]]])

In [ ]:
# Shape Interpretation: a 5 by 5 in the 1st dimension
TENSOR.shape

torch.Size([1, 4, 5])

Random Tensors

Why random tensors?

Random tensors are important because the way way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data (Remember weights and biases).

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5818, 0.9439, 0.1940, 0.3618],
        [0.1933, 0.3617, 0.5393, 0.5877],
        [0.7242, 0.4849, 0.6638, 0.7606]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, weight, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
### Zeros and Ones

#Create a tensor of all zeros
zero_tensor = torch.zeros(size=(3, 4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
one_tensor = torch.ones(size=(3, 4))
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Use torch.range()
Basic_10 = torch.arange(1, 11)
print(Basic_10)
a = torch.arange(start=0, end=1000, step=77)
print(a)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


In [ ]:
# Creating tensors "like" another tensor
ten_zeros = torch.zeros_like(input=Basic_10)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes is one of the big 3 errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (eg float 32 or float 16)
                               device = None, # what device is your tensor on (default is cpu)
                               requires_grad = False) # whether or not to track gradients with tensor operations

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors (attributes)

Tensors not right datatype - to get datatype of tensor, use tensor.dtype

Tensors not right shape - to get shape of a tensor, can use tensor.shape

Tensors not on the right device - to get device of a tensor, can use tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0502, 0.3593, 0.1673, 0.6573],
        [0.3692, 0.6274, 0.8235, 0.1867],
        [0.6138, 0.8122, 0.3270, 0.2095]])

In [ ]:
# Find out details about some tensor:

print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


Tensor Operations
- Addition
- Subrtaction
- Multiplication
- Division
- Matrix Multiplication (dot product)

In [ ]:
# Manipulating Tensors (tensor operations)
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
some_tensor, some_tensor.T #transposing tensors with torch.transpose(tensor, 0, 1)

(tensor([[0.0502, 0.3593, 0.1673, 0.6573],
         [0.3692, 0.6274, 0.8235, 0.1867],
         [0.6138, 0.8122, 0.3270, 0.2095]]),
 tensor([[0.0502, 0.3692, 0.6138],
         [0.3593, 0.6274, 0.8122],
         [0.1673, 0.8235, 0.3270],
         [0.6573, 0.1867, 0.2095]]))

In [ ]:
# Find max/min
some_tensor.max()
torch.min(some_tensor)

tensor(0.0502)

In [ ]:
some_tensor.argmax() # position of maxvalue (like which index)

tensor(6)

In [ ]:
## Reshaping, stacking, squeezing, and unsqueezing

## Reshaping, stacking, squeezing, and unsqueezing

- Reshaping: reshapes an input tensor to a defined shape
- View: View of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking: Combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze: removes all 1 dimension from a tensor
- Unsqueeze: Add a 1 dimension to a target tensor
- Permute: Return a view of the input with dimensions permuted (swapped) in a certain way.


In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")


#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specific order
x_original = torch.rand(size = (224, 224, 3)) # [height, width, colour_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0 to 1, 1 to 2, 2 to 0

print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
# Create tensor
y = torch.arange(1, 10).reshape(1, 3, 3)
y, y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Lets index on the middle bracket (dim=1)
y[0][0]

tensor([1, 2, 3])

In [ ]:
# Lets index on the most inner bracket (last dimension)
y[0][0][0]

tensor(3)

In [ ]:
# Getting 9, practice
y[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
y[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
y[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
y[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2n dimension
y[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on y to return 9
y[0, 2, 2]

tensor(9)

In [ ]:
# Index on y to return 3, 6, 9

y[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor - torch.from_numpy(ndarray)

*Data in torch to numPy - torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor
# Default dtype for NP is float64 while a torch tensor default is float32
# Warning - when converting from a NP to a torch tensor, the default will be float64 unless changed
import numpy as np

array = np.arange(1.0, 8.0)
c = torch.from_numpy(array)
array, c

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

When converting from np to tensor or other way around, changes to original array or tensor does not change the new tensor or array

Any new tensor or array will reflect the dtype of the original array or tensor

### To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
## Reproducbility (trying to take random out of random)

# Create two random tensors
rand_tensor_A = torch.rand(3,4)
rand_tensor_B = torch.rand(3,4)

print(rand_tensor_A)
print(rand_tensor_B)
print(rand_tensor_A == rand_tensor_B)

tensor([[0.5743, 0.2899, 0.2480, 0.6302],
        [0.2786, 0.0713, 0.8340, 0.8473],
        [0.6368, 0.6624, 0.6290, 0.1507]])
tensor([[0.2489, 0.3275, 0.5604, 0.7476],
        [0.6524, 0.6625, 0.8848, 0.1226],
        [0.3409, 0.1713, 0.7965, 0.2228]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducable tensors

#Set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility: https://docs.pytorch.org/docs/stable/notes/randomness.html

### 1. Getting a GPU

- Easiest: Use Google Colab for a free GPU (options to upgrade as well)
- Use your own GPU
- Use cloud computing
Device agnostic code - https://docs.pytorch.org/docs/stable/notes/cuda.html

In [ ]:
# Putting tensors (and models) on the GPU
# For now stick with CPU, but ifneeded in future look to run on Colab GPU


In [ ]:
# Create a tensor
d = torch.tensor([1, 2, 3])
d, d.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
## Exercises and Extracurriculars